@Channels = new Meteor.Collection "channels"
@CompositeChannels = new Meteor.Collection "composite_channels"
@Programs = new Meteor.Collection "programs"
@Relations = new Meteor.Collection "relations"
@UnknownPrograms = new Meteor.Collection "unknown_programs"
@Recommendations = new Meteor.Collection "recommendations"
